### ISSUE TITLE
Guidance on Uploading Data Folders for Google Colab Users

### ISSUE THREAD

**Issue by danielrazavi** [UofT-DSI/03-python#7]
https://github.com/UofT-DSI/03-python/blob/2023-course-materials/01-slides/00_hello_python.ipynb

Assuming this is the first time they are working with Google Colab, they may simply upload this file to their Google Colab accounts and expect it to work. However, when they run the Python cells, since they were never explicitly shown or told to upload the data folder alongside it, the execution results in an error. Is there a set of instructions where learners can follow to upload the data folder?

**Comment by kaylielau** [comment]
If files are uploaded directly to a Colab session, they will not persist across different sessions or if the runtime is disconnected or restarted. To mitigate this, I decided to have students upload the data folder to Google Drive and subsequently in each class we will mount it in the Colab environment. I have updated the slides to include more detailed instructions on how to download the GitHub repo, upload the data folder to Google Drivel and mount it in the Colab environment.
