### ISSUE TITLE
Is Relocating the ".ipynb_checkpoints" Folder to Its Own Branch Beneficial for Learners?

### ISSUE THREAD

**Issue by danielrazavi** [UofT-DSI/03-python#8]
In many operating systems, the convention is to use a dot (.) at the beginning of a file name to indicate that it's hidden. [.ipynb_checkpoints](https://github.com/UofT-DSI/03-python/tree/2023-course-materials/01-slides/.ipynb_checkpoints) directory follows this naming convention. Would it be beneficial to move it to its own branch, hidden away from learners?

**Comment by kaylielau** [comment]
It might not be necessary or beneficial to move the .ipynb_checkpoints directory to its own branch, but I will make sure to briefly explain the purpose of these files and advise students to ignore these hidden directories while focusing on their main learning objectives.
